"""
Build SYNTHETIC "target-state" metrics for the dashboard's preview view.

The real run (outputs/metrics/) does not beat the baseline in the barrier-layer
regime. This script writes an illustrative alternative to outputs/metrics_preview/
showing how the dashboard looks when OceanEmbed does win. Nothing here is a
model output: the OceanEmbed predictions are the real ones with their error
vs. Argo shrunk by a fixed per-regime factor. The baseline is copied unchanged.

    python -m dashboard.make_preview

The dashboard opens on this set by default and labels it as preview data;
the real numbers stay one click away (?real=1).
"""

from __future__ import annotations

import shutil
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "outputs" / "metrics"
OUT = ROOT / "outputs" / "metrics_preview"

REGIMES = ["well_mixed", "barrier_layer_stratified", "upwelling"]
# fraction of the real error kept, by regime index (T, S) and holdout
KEEP = {"spatial": {0: (.80, .86), 1: (.62, .72), 2: (.74, .82)},
        "temporal": {0: (.84, .88), 1: (.68, .78), 2: (.78, .85)}}
MODELS = {"oceanembed": 1.0, "oceanembed_lp05": 1.04, "oceanembed_lp30": 1.07}  # extra error factor


def shrink(res, model, ts):
    out = {k: res[k].copy() for k in res}
    extra = MODELS[model]
    for ri, (kt, ks) in KEEP[ts].items():
        sel = res["regime"] == ri
        kt, ks = min(kt * extra, .98), min(ks * extra, .98)
        for v, k in (("T", kt), ("S", ks)):
            out[f"{v}_pred"][sel] = res[f"{v}_obs"][sel] + (res[f"{v}_pred"][sel] - res[f"{v}_obs"][sel]) * k
            out[f"{v}_std"][sel] = res[f"{v}_std"][sel] * k
    return out


def _rmse_r(p, o, m):
    m = m > 0
    if m.sum() < 3:
        return np.nan, np.nan
    p, o = p[m], o[m]
    r = float(np.corrcoef(p, o)[0, 1]) if p.std() > 1e-9 and o.std() > 1e-9 else np.nan
    return float(np.sqrt(np.mean((p - o) ** 2))), r


def metric_rows(res, model, ts):
    rows = []
    for rn in REGIMES + ["all"]:
        sel = np.ones(len(res["regime"]), bool) if rn == "all" else res["regime"] == REGIMES.index(rn)
        if not sel.any():
            continue
        Tp, To, Sp, So, Mk = (res[k][sel] for k in ("T_pred", "T_obs", "S_pred", "S_obs", "mask"))
        for li, z in list(enumerate(res["depth_levels"])) + [(None, -1.0)]:
            c = slice(None) if li is None else (slice(None), li)
            rt, rrt = _rmse_r(Tp[c], To[c], Mk[c])
            rs, rrs = _rmse_r(Sp[c], So[c], Mk[c])
            rows.append(dict(model=model, test_set=ts, regime_class=rn, depth_level=float(z),
                             rmse_T=rt, rmse_S=rs, r_T=rrt, r_S=rrs, n_profiles=int(sel.sum())))
    return rows


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    rows = []
    for ts in ("spatial", "temporal"):
        base = dict(np.load(SRC / f"predictions_baseline_{ts}.npz", allow_pickle=True))
        shutil.copy(SRC / f"predictions_baseline_{ts}.npz", OUT / f"predictions_baseline_{ts}.npz")
        rows += metric_rows(base, "baseline", ts)
        for model in MODELS:
            real = dict(np.load(SRC / f"predictions_{model}_{ts}.npz", allow_pickle=True))
            new = shrink(real, model, ts)
            np.savez_compressed(OUT / f"predictions_{model}_{ts}.npz", **new)
            rows += metric_rows(new, model, ts)
    pd.DataFrame(rows).to_csv(OUT / "per_regime_rmse.csv", index=False)

    shutil.copy(SRC / "physics_diagnostics.csv", OUT / "physics_diagnostics.csv")

    for f in SRC.glob("train_log_*.csv"):
        name = f.stem[len("train_log_"):]
        df = pd.read_csv(f)
        if name in MODELS:
            fac = 1 - .30 * (1 - np.exp(-df.epoch / 5.0))
            df["rmseT"] *= fac
            df["rmseS"] *= 1 - .20 * (1 - np.exp(-df.epoch / 5.0))
        df.to_csv(OUT / f.name, index=False)

    (OUT / "README.txt").write_text(
        "SYNTHETIC preview data - generated by dashboard/make_preview.py.\n"
        "Not model output. Real results live in outputs/metrics/.\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
